name: Audit Wiki Links
on:
  schedule:
    - cron: '0 0 1 * * ' # Once a month
  workflow_dispatch: # Or manually from GitHub UI
  push:
    branches:
      - '#3970' # Debug

jobs:
  Audit_Links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Pull repo
        run: |
          git config --global user.email "polkadot-kusama-automation-bot@users.noreply.github.com"
          git config --global user.name "Polkadot-Kusama Bot"
          git branch audit-links
          git checkout audit-links
      
      - name: Execute python
        run: |
          python -m pip install --upgrade pip
          pip install requests
          OUTPUT=$(python './scripts/auditLinks.py')
          echo "{AUDIT_RESULTS}={OUTPUT}" >> $GITHUB_ENV
      
      - name: Check results for broken links
        run: |
          echo Results:
          echo "${{ env.AUDIT_RESULTS }}" 